### ISSUE TITLE
PayPal Payments Failing

### ISSUE THREAD

**Issue by nickster13x** [woocommerce/woocommerce-paypal-payments#1608]
WooCommerce PayPal Payments are not working.

Error message:

Payment for order# ---  from Michael ------ has failed. The order was as follows:

The subscription payment failed because the payment method could not be saved. 
Please try again with a different payment method.

Payment method: | PayPal

PayPal Log:

2023-07-24T00:36:28+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on bool in /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/lifterlms-assignments/includes/functions-llms-assignments-templates.php:163
Stack trace:
#0 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/class-wp-hook.php(308): llms_assignments_after_start_quiz_buttons('')
#1 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/lifterlms/templates/quiz/start-button.php(81): do_action('lifterlms_after...')
#4 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include('/chroot/home/ae...')
#5 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/lifterlms/includes/functions/llms.functions.templates.quizzes.php(217): llms_get_template('quiz/start-butt...')
#6 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/class-wp-hook.php(308): lifterlms_template_start_button('')
#7 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#8 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/lifterlms/templates/content-single-quiz-after.php(11): do_action('lifterlms_singl...')
#10 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/template.php(785): require('/chroot/home/ae...')
#11 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/lifterlms/includes/functions/llms-functions-content.php(56): load_template('/chroot/home/ae...', false)
#12 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/class-wp-hook.php(308): llms_get_post_content('<p>Welcome to t...')
#13 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/plugin.php(205): WP_Hook->apply_filters('<p>Welcome to t...', Array)
#14 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/formatting.php(3928): apply_filters('the_content', '<p>Welcome to t...')
#15 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/class-wp-hook.php(308): wp_trim_excerpt('<p>Welcome to t...', Object(WP_Post))
#16 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#17 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/post-template.php(431): apply_filters('get_the_excerpt', '', Object(WP_Post))
#18 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/post-template.php(396): get_the_excerpt()
#19 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(965): the_excerpt()
#20 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(1281): ElementorPro\Modules\Posts\Skins\Skin_Base->render_excerpt()
#21 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(876): ElementorPro\Modules\Posts\Skins\Skin_Base->render_post()
#22 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/skins/posts-archive-skin-base.php(54): ElementorPro\Modules\Posts\Skins\Skin_Base->render()
#23 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\ThemeBuilder\Skins\Posts_Archive_Skin_Classic->render()
#24 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode()
#25 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#26 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Widget_Base->print_content()
#27 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/includes/base/element-base.php(1354): Elementor\Element_Base->print_element()
#28 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Element_Base->print_content()
#29 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/includes/base/element-base.php(1354): Elementor\Element_Base->print_element()
#30 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Element_Base->print_content()
#31 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/core/base/document.php(1711): Elementor\Element_Base->print_element()
#32 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(418): Elementor\Core\Base\Document->print_elements(Array)
#33 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/includes/frontend.php(1179): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array)
#34 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/core/base/document.php(1155): Elementor\Frontend->get_builder_content(189, false)
#35 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document->get_content(false)
#36 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document->get_content(false)
#37 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content()
#38 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(315): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content()
#39 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(191): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location('archive')
#40 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->ElementorPro\Modules\ThemeBuilder\Classes\{closure}()
#41 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/modules/page-templates/module.php(207): call_user_func(Object(Closure))
#42 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(19): Elementor\Modules\PageTemplates\Module->print_content()
#43 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-includes/template-loader.php(106): include('/chroot/home/ae...')
#44 /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-blog-header.php(19): require_once('/chroot/home/ae...')
#45 /chroot/home/ae328251/f63c153390.nxcli.net/html/index.php(17): require('/chroot/home/ae...')
#46 {main}
  thrown in /chroot/home/ae328251/f63c153390.nxcli.net/html/wp-content/plugins/lifterlms-assignments/includes/functions-llms-assignments-templates.php on line 163

### Expected Behavior

Students purchase a course subscription and expected to receive the course.

### Actual Behavior

Payments failed (numerous)

### Environment

 - WordPress Version 6.3
 - WooCommerce Version 8.02
 - Plugin Version 2.2.0
 - Browser: Chrome
 - Any other plugins installed

<html>
<body>

Advanced Shipment Tracking for WooCommerce | Version 3.5.3 by zorem \| Auto-updates disabled
-- | --
Akismet Anti-Spam: Spam Protection | Version 5.2 by Automattic - Anti Spam Team \| Auto-updates enabled
All-in-One WP Migration | Version 7.77 by ServMask \| Auto-updates disabled
Autocomplete WooCommerce Orders | Version 3.1.3 by QuadLayers \| Auto-updates disabled
CookieYes \| GDPR Cookie Consent | Version 3.1.2 by CookieYes \| Auto-updates disabled
Dynamic Visibility for Elementor | Version 5.0.6 by Dynamic.ooo \| Auto-updates disabled
Elementor | Version 3.15.2 by Elementor.com \| Auto-updates disabled
Elementor Pro | Version 3.15.1 by Elementor.com \| Auto-updates disabled
Embed PDF Viewer | Version 2.3.0 by Andy Fragen \| Auto-updates disabled
Imagify | Version 2.1.1 by Imagify – Optimize Images & Convert WebP \| Auto-updates disabled
Integration for WooCommerce and Zoho Pro | Version 1.4.2 by CRM Perks \| Auto-updates disabled
Jetpack | Version 12.4 by Automattic \| Auto-updates disabled
Kadence WooCommerce Email Designer | Version 1.5.11 by Kadence WP \| Auto-updates disabled
LifterLMS | Version 7.3.0 by LifterLMS \| Auto-updates disabled
LifterLMS Advanced Quizzes | Version 3.0.0 by LifterLMS \| Auto-updates disabled
LifterLMS Advanced Videos | Version 1.0.0-beta.20 by LifterLMS \| Auto-updates disabled
LifterLMS Assignments | Version 2.1.0 by LifterLMS \| Auto-updates disabled
LifterLMS Custom Fields | Version 2.0.2 by LifterLMS \| Auto-updates disabled
LifterLMS Customizations | Version 1.0.0 by codeBOX \| Auto-updates disabled
LifterLMS Groups | Version 1.0.0-beta.21 by LifterLMS \| Auto-updates disabled
LifterLMS Helper | Version 3.5.0 by LifterLMS \| Auto-updates disabled
LifterLMS PDFs | Version 2.2.1 by LifterLMS \| Auto-updates disabled
LifterLMS Twilio | Version 2.0.0 by LifterLMS \| Auto-updates disabled
LifterLMS WooCommerce | Version 2.2.2 by Team LifterLMS \| Auto-updates disabled
LifterLMS WPForms | Version 1.1.2 by LifterLMS \| Auto-updates disabled
ManageWP - Worker | Version 4.9.17 by GoDaddy \| Auto-updates disabled
MonsterInsights - eCommerce Addon | Version 8.4.0 by MonsterInsights Team \| Auto-updates disabled
MonsterInsights Pro | Version 8.18 by MonsterInsights \| Auto-updates disabled
PDF Invoices & Packing Slips for WooCommerce | Version 3.6.1 by WP Overnight \| Auto-updates disabled
Redirection | Version 5.3.10 by John Godley \| Auto-updates disabled
Tangible: Lifter Elements | Version 1.4.1 by Team Tangible \| Auto-updates disabled
TrackShip for WooCommerce | Version 1.6.3 by TrackShip \| Auto-updates disabled
Ultimate Gift Cards For WooCommerce | Version 2.5.5 by WP Swings \| Auto-updates disabled
UpdraftPlus - Backup/Restore | Version 1.23.9 by UpdraftPlus.Com, DavidAnderson \| Auto-updates enabled
User Switching | Version 1.7.0 by John Blackbourn & contributors \| Auto-updates disabled
WooCommerce | Version 8.0.2 by Automattic \| Auto-updates disabled
WooCommerce Payments | Version 6.3.2 by Automattic \| Auto-updates disabled
WooCommerce PayPal Payments | Version 2.2.0 by WooCommerce \| Auto-updates disabled
WooCommerce Shipping & Tax | Version 2.3.2 by WooCommerce \| Auto-updates disabled
WooCommerce Stripe Gateway | Version 7.5.0 by WooCommerce \| Auto-updates disabled
WooCommerce Subscriptions | Version 5.4.0 by WooCommerce \| Auto-updates disabled
WooCommerce Subscriptions - Delete Cancel Subscription Confirmation | Version 1.0 by Prospress Inc. \| Auto-updates disabled
WooCommerce Zapier | Version 2.3.1 by OM4 Software (Latest version: 2.7.2) \| Auto-updates disabled
WPForms | Version 1.8.3.2 by WPForms \| Auto-updates disabled
WPForms User Journey | Version 1.0.6 by WPForms \| Auto-updates disabled
WPForms User Registration | Version 2.2.0 by WPForms \| Auto-updates disabled
WPForms Zapier | Version 1.5.0 by WPForms \| Auto-updates disabled
WPMerge | Version 1.2.9 by Revmakx \| Auto-updates disabled
WP Rocket | Version 3.13.1 by WP Media \| Auto-updates disabled
Yoast SEO | Version 20.13 by Team Yoast \| Auto-updates disabled
Yoast SEO Premium | Version 20.5 by Team Yoast (Latest version: 20.13) \| Auto-updates disabled
Yoast Test Helper | Version 1.17 by Team Yoast \| Auto-updates disabled
Zoho Campaigns | Version 2.0.6 by Zoho Campaigns \| Auto-updates disabled

</body>
</html>

### Additional Details

This is happening to numerous users

WooCommerce Support: Ticket #6675276

Users purchasing courses on nlcprep.com are expecting to have access to a course, but are notified of the payment error referenced above.

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by nickster13x** [comment]
I just received feedback from the above referenced ticket. 
I modified the Vault settings to accept payments and disregard payment methods.
Thank you!

**Comment by nickster13x** [comment]
See above - last comment. Thanks!
