### ISSUE TITLE
PHP Warnings: Undefined property: stdClass::$avs_code & stdClass::$cvv_code in FraudProcessorResponseFactory.php

### ISSUE THREAD

**Issue by bashgeek** [woocommerce/woocommerce-paypal-payments#1680]
### Describe the Bug

If a payment is denied by the payment provider, PHP warnings about undefined properties appear in our log. To our knowledge this happens every time a payment method is declined.

### To Reproduce

Apparently use a credit card that gets declined on payment and causes a "Payment provider declined the payment, please use a different payment method." error and observe the PHP error log.

### Expected Behavior

Do not cause warnings.

### Actual Behavior

Throws following warnings in the PHP log:
```
[09-Sep-2023 03:25:00 UTC] PHP Warning:  Undefined property: stdClass::$avs_code in wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/FraudProcessorResponseFactory.php on line 28
[09-Sep-2023 03:25:00 UTC] PHP Warning:  Undefined property: stdClass::$cvv_code in wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/FraudProcessorResponseFactory.php on line 29
[09-Sep-2023 03:27:06 UTC] PHP Warning:  Undefined property: stdClass::$avs_code in wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/FraudProcessorResponseFactory.php on line 28
[09-Sep-2023 03:27:06 UTC] PHP Warning:  Undefined property: stdClass::$cvv_code in wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/FraudProcessorResponseFactory.php on line 29
```

### Environment

 - WordPress Version: 6.3.1
 - WooCommerce Version: 8.0.3
 - Plugin Version: 2.2.2

### Additional Details

The following log entries appear in the plugins debug log at the same time as the mentioned warnings above:
```
2023-09-09T03:25:00+00:00 ERROR Payment failed: Payment provider declined the payment, please use a different payment method. OrderEndpoint.php:358
2023-09-09T03:27:06+00:00 ERROR Payment failed: Payment provider declined the payment, please use a different payment method. OrderEndpoint.php:358
```

**Comment by Sirvijver** [comment]
Hello @bashgeek 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

For now, I have quickly done a test with a declined card payment (INSTRUMENT_DECLINED) on a clean testing environment, to verify if this PHP error would also show up, but in my case it did not.
Can you do a similar test with all other plugins (except WooCommerce and PayPal Payments) being deactivated and while using the [Default storefront theme](https://wordpress.org/themes/storefront/)?
I would expect that another element on your site might be affecting the stdClass and this to be causing the conflict with our plugin.

If this does not help, and you still need our support, I would advise you to open the support request as mentioned above. This thread will be closed.

Kind regards, 
Joost

**Comment by bashgeek** [comment]
@Sirvijver Thanks for your reply. We do not have any plugins that interfere with payments, it's a pretty vanilla setup there. I did some more digging into it and it appears it does not happen on every declined payment and only occasionally, something seems to be different in the response Paypal is delivering, but I can't see what exactly because the response is not part of the debug logs.

However, I was able to obtain a full stack-trace that maybe helps with it:

```
ErrorException: Warning: Undefined property: stdClass::$cvv_code
#24 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/FraudProcessorResponseFactory.php(29): WooCommerce\PayPalCommerce\ApiClient\Factory\FraudProcessorResponseFactory::from_paypal_response
#23 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/CaptureFactory.php(74): WooCommerce\PayPalCommerce\ApiClient\Factory\CaptureFactory::from_paypal_response
#22 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/PaymentsFactory.php(77): WooCommerce\PayPalCommerce\ApiClient\Factory\PaymentsFactory::WooCommerce\PayPalCommerce\ApiClient\Factory\{closure}
#21 [internal](0): array_map
#20 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/PaymentsFactory.php(75): WooCommerce\PayPalCommerce\ApiClient\Factory\PaymentsFactory::from_paypal_response
#19 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/PurchaseUnitFactory.php(284): WooCommerce\PayPalCommerce\ApiClient\Factory\PurchaseUnitFactory::from_paypal_response
#18 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/OrderFactory.php(138): WooCommerce\PayPalCommerce\ApiClient\Factory\OrderFactory::WooCommerce\PayPalCommerce\ApiClient\Factory\{closure}
#17 [internal](0): array_map
#16 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/OrderFactory.php(136): WooCommerce\PayPalCommerce\ApiClient\Factory\OrderFactory::from_paypal_response
#15 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php(357): WooCommerce\PayPalCommerce\ApiClient\Endpoint\OrderEndpoint::capture
#14 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Processor/OrderProcessor.php(221): WooCommerce\PayPalCommerce\WcGateway\Processor\OrderProcessor::process
#13 /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/CreditCardGateway.php(390): WooCommerce\PayPalCommerce\WcGateway\Gateway\CreditCardGateway::process_payment
#12 /wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1050): WC_Checkout::process_order_payment
#11 /wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1279): WC_Checkout::process_checkout
#10 /wp-content/plugins/woocommerce/includes/class-wc-ajax.php(508): WC_AJAX::checkout
#9 /wp-includes/class-wp-hook.php(310): WP_Hook::apply_filters
#8 /wp-includes/class-wp-hook.php(334): WP_Hook::do_action
#7 /wp-includes/plugin.php(517): do_action
#6 /wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): WC_AJAX::do_wc_ajax
#5 /wp-includes/class-wp-hook.php(310): WP_Hook::apply_filters
#4 /wp-includes/class-wp-hook.php(334): WP_Hook::do_action
#3 /wp-includes/plugin.php(517): do_action
#2 /wp-includes/template-loader.php(13): require_once
#1 /wp-blog-header.php(19): require
#0 /index.php(17): null
```
