### ISSUE TITLE
ShipStation Integration issue with 2.4.1: Too few arguments to function ShipStationIntegration.php:74

### ISSUE THREAD

**Issue by dream-encode** [woocommerce/woocommerce-paypal-payments#1851]
### Describe the Bug

Updated to 2.4.1 on Wednesday, and since, ShipStation is showing an error when posting back to WooCommerce.   Attaching error in ShipStation.

Checked logs, and found this CRITICAL occurring every time this happens:
```
2023-11-17T15:30:59+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function WooCommerce\PayPalCommerce\OrderTracking\Integration\ShipStationIntegration::WooCommerce\PayPalCommerce\OrderTracking\Integration\{closure}(), 1 passed in /path/wp-includes/class-wp-hook.php on line 326 and exactly 2 expected in /path/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Integration/ShipStationIntegration.php:74
Stack trace:
#0 /path/wp-includes/class-wp-hook.php(326): WooCommerce\PayPalCommerce\OrderTracking\Integration\ShipStationIntegration->WooCommerce\PayPalCommerce\OrderTracking\Integration\{closure}(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /path/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /path/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /path/wp-content/plugins/woocommerce-shipstation-integration/includes/api-requests/class-wc-shipstation-api-shipnotify.php(334): do_action('woocommerce_shi...', Object(Automattic\WooCommerce\Admin\Overrides\Order), Array)
#4 /path/wp-content/plugins/woocommerce-shipstation-integration/includes/class-wc-shipstation-api.php(80): WC_Shipstation_API_Shipnotify->request()
#5 /path/wp-content/plugins/woocommerce-shipstation-integration/includes/class-wc-shipstation-api.php(37): WC_Shipstation_API->request()
#6 /path/wp-content/plugins/woocommerce-shipstation-integration/includes/class-wc-shipstation-api.php(89): WC_Shipstation_API->__construct()
#7 /path/wp-content/plugins/woocommerce-shipstation-integration/woocommerce-shipstation.php(81): include_once('/path...')
#8 /path/wp-includes/class-wp-hook.php(324): woocommerce_shipstation_api('')
#9 /path/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#10 /path/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /path/wp-content/plugins/woocommerce/includes/class-wc-api.php(161): do_action('woocommerce_api...')
#12 /path/wp-includes/class-wp-hook.php(324): WC_API->handle_api_requests(Object(WP))
#13 /path/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#14 /path/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#15 /path/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#16 /path/wp-includes/class-wp.php(813): WP->parse_request('')
#17 /path/wp-includes/functions.php(1336): WP->main('')
#18 /path/wp-blog-header.php(16): wp()
#19 /path/index.php(17): require('/path...')
#20 {main}
  thrown in /path/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Integration/ShipStationIntegration.php on line 74
	}
```

### To Reproduce
 
1. Have an order placed.
2. Attempt to ship order from ShipStation.

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1900750/78b32f08-6ab1-4bd1-9b33-05a0dd9a6796)

### Expected Behavior

No errors should be received when shipping orders in ShipStation.

### Actual Behavior

Received error show in screenshot and log is filled with entries posted above.

### Environment

WP 6.4.1
WC 8.2.2
PayPal 2.4.1
ShipStation 4.3.9
</details>

**Comment by InpsydeNiklas** [comment]
Hi @dream-encode, changing the [value here](https://github.com/woocommerce/woocommerce-paypal-payments/pull/1841/files) should resolve the error and result in the tracking data automatically being sent to PayPal. Please let us know how this works for you. Thanks!
