### ISSUE TITLE
CRITICAL Uncaught Error

### ISSUE THREAD

**Issue by timmac-qmc** [woocommerce/woocommerce-paypal-payments#1937]
### Describe the Bug

Customer trying to checkout using Debit Card, triggers the following error when returning to the site after payment

### To Reproduce

1. Checkout using Debit card
2. Return the site after Payment

### Expected Behavior

Payment should be completed

### Actual Behavior

Site throws exception

### Environment

 - WordPress Version: 6.4.2
 - WooCommerce Version: 8.4.0 
 - Plugin Version:  2.4.2
 - Browser [e.g. Chrome, Safari] and Version: Any
 - Any other plugins installed: 

### Additional Details

Stack Trace:

```
2024-01-02T10:20:36+00:00 CRITICAL Uncaught Error: Call to a member function id() on null in /home/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayPalGateway.php:614
Stack trace:
#0 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(449): WooCommerce\PayPalCommerce\WcGateway\Gateway\PayPalGateway->process_payment(10521)
#1 /home/public_html/wp-includes/class-wp-hook.php(324): WC_Form_Handler::pay_action(Object(WP))
#2 /home/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /home/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#4 /home/public_html/wp-includes/class-wp.php(830): do_action_ref_array('wp', Array)
#5 /home/public_html/wp-includes/functions.php(1336): WP->main('')
#6 /home/public_html/wp-blog-header.php(16): wp()
#7 /home/public_html/index.php(17): require('/home/...')
#8 {main}
  thrown in /home/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/PayPalGateway.php on line 614
```

<details><summary>System status</summary>

  ```
`
### wp-core ###

version: 6.4.2
site_language: en_GB
user_language: en_GB
timezone: Europe/London
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 40
dotorg_communication: true

### wp-paths-sizes ###

wordpress_size: 68.75 MB (72086399 bytes)
uploads_size: 8.92 GB (9582332107 bytes)
themes_size: 11.08 MB (11614265 bytes)
plugins_size: 117.29 MB (122985361 bytes)
database_size: 155.48 MB (163037184 bytes)
total_size: 9.27 GB (9952055316 bytes)

### wp-dropins (2) ###

advanced-cache.php: true
maintenance.php: true

### wp-themes-inactive (1) ###

Twenty Twenty-Four: version: 1.0, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

InfiniteWP - Client Loader: version: 1.0.1, author: Revmakx

### wp-plugins-active (39) ###

a3 Lazy Load: version: 2.7.1, author: a3rev Software, Auto-updates disabled
AddToAny Share Buttons: version: 1.8.9, author: AddToAny, Auto-updates disabled
Advanced Custom Fields PRO: version: 6.2.4, author: WP Engine, Auto-updates disabled
All in One SEO: version: 4.5.3.1, author: All in One SEO Team, Auto-updates disabled
Attachment Pages Redirect: version: 1.1.2, author: Samuel Aguilera, Auto-updates disabled
Breadcrumb NavXT: version: 7.2.0, author: John Havlik, Auto-updates disabled
Classic Editor: version: 1.6.3, author: WordPress Contributors, Auto-updates disabled
Code Snippets: version: 3.6.2, author: Code Snippets Pro, Auto-updates disabled
Crop Thumbnails: version: 1.8.0, author: Volkmar Kantor, Auto-updates disabled
Custom Facebook Feed Pro - Extensions: version: 1.7.3, author: Smash Balloon, Auto-updates disabled
Custom Facebook Feed Pro Smash: version: 4.5.2, author: Smash Balloon, Auto-updates disabled
Custom Twitter Feeds Pro Developer: version: 2.3.1, author: Smash Balloon, Auto-updates disabled
Feeds for YouTube Pro Developer: version: 2.2.3, author: Smash Balloon, Auto-updates disabled
Flow-Flow: version: 4.6.4, author: Looks Awesome, Auto-updates disabled
Imagify: version: 2.1.3, author: Imagify – Optimize Images & Convert WebP, Auto-updates disabled
InfiniteWP - Client: version: 1.12.4, author: Revmakx, Auto-updates disabled
Innermedia High Vis: author: (undefined), version: 0.1, Auto-updates disabled
Instagram Feed Pro Developer: version: 6.3.4, author: Smash Balloon, Auto-updates disabled
iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: version: 3.9.0, author: iubenda, Auto-updates disabled
MCE Table Buttons: version: 3.3.1, author: Jake Goldman, 10up, Oomph, Auto-updates disabled
Members: version: 3.2.9, author: MemberPress, Auto-updates disabled
Redirection: version: 5.4, author: John Godley, Auto-updates disabled
Regenerate Thumbnails: version: 3.1.6, author: Alex Mills (Viper007Bond), Auto-updates disabled
Relevanssi: version: 4.21.1, author: Mikko Saari, Auto-updates disabled
Search & Replace: version: 3.2.1, author: Inpsyde GmbH, Auto-updates disabled
Smart Slider 3: version: 3.5.1.21, author: Nextend, Auto-updates disabled
Smash Balloon Social Wall: version: 2.1, author: Smash Balloon, Auto-updates disabled
Solid Security Basic: version: 9.2.0, author: SolidWP, Auto-updates disabled
Ultimate Twitter Feeds: version: 0.1, author: Ultimate Twitter Feeds Devs, Auto-updates enabled
WooCommerce: version: 8.4.0, author: Automattic, Auto-updates disabled
WooCommerce PayPal Payments: version: 2.4.2, author: WooCommerce, Auto-updates disabled
WP-Sweep: version: 1.1.8, author: Lester 'GaMerZ' Chan, Auto-updates disabled
WP Crontrol: version: 1.16.1, author: John Blackbourn & crontributors, Auto-updates disabled
WPForms: version: 1.8.5.4, author: WPForms, Auto-updates disabled
WPForms Signatures: version: 1.8.0, author: WPForms, Auto-updates disabled
WP Media folder: version: 5.8.0, author: Joomunited, Auto-updates enabled
WP Rocket: version: 3.15.6, author: WP Media, Auto-updates disabled
wp_mail return-path: version: 1.1.1, author: Barnaby Puttick, Auto-updates disabled
Yoast Duplicate Post: version: 4.5, author: Enrico Battocchi & Team Yoast, Auto-updates disabled

### wp-plugins-inactive (10) ###

Autoptimize: version: 3.1.10, author: Frank Goossens (futtta), Auto-updates disabled
CookieYes | GDPR Cookie Consent: version: 3.1.7, author: CookieYes, Auto-updates disabled
GDPR/CCPA Cookie Consent Banner: version: 3.1.1, author: Termly, Auto-updates disabled
Google Analytics for WordPress by MonsterInsights: version: 8.23.1, author: MonsterInsights, Auto-updates disabled
iThemeland WooCommerce Bulk Orders Editing Lite: version: 2.2.2, author: iThemelandco, Auto-updates disabled
OptinMonster: version: 2.15.1, author: OptinMonster Popup Builder Team, Auto-updates disabled
WooPayments: version: 6.9.2, author: Automattic, Auto-updates disabled
WP Fastest Cache: version: 1.2.2, author: Emre Vona, Auto-updates disabled
WP Mourning: version: 1.0, author: Chanon Srithongsook, Auto-updates disabled
XML Sitemap Generator for Google: version: 4.1.16, author: Auctollo, Auto-updates disabled

### code-snippets (1) ###

snippet-5: name: Add Order Completed BCC, scope: global, modified: 2023-12-19 10:47:14

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 48M
upload_max_filesize: 48M
max_effective_size: 48 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 1.844674407371E+19
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-167-generic x86_64
httpd_software: Apache
php_version: 8.1.26 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 30
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 48M
php_post_max_size: 48M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-01-02T11:34:36+00:00
utc-time: Tuesday, 02-Jan-24 11:34:36 UTC
server-time: 2024-01-02T11:34:34+00:00

### wp-database ###

extension: mysqli
server_version: 8.0.35
client_version: mysqlnd 8.1.26
max_allowed_packet: 268435456
max_connections: 5000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### aioseo (1) ###

noindexed: Author Archives, Date Archives, Search Page

### wpforms ###

version: 1.8.5.4
pro: 6 July 2021 at 12:23 pm
upload_dir: Writable
total_forms: 5
total_entries: 8367
license_status: Valid
license: Elite
license_location: option

`
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @timmac-qmc, this error is caused by a third-party plugin. I recommend performing a conflict test to understand which other plugin causes the error as it should not persist with only WooCommerce and PayPal Payments active: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

In any case, our support team is happy to assist should you need additional guidance: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thanks!
