### ISSUE TITLE
Issues with removing products from cart

### ISSUE THREAD

**Issue by morganhvidt** [woocommerce/woocommerce-paypal-payments#2018]
### Describe the Bug

I have plugin which reserves product stock during the add to cart functions, it also releases the reservation if the product is removed from the cart. 

The issue is the PayPal gateway has various functions which appear to remove products/cart, just to restore the cart again from a variable. 

This triggers hooks such as `woocommerce_cart_item_removed` wrongly, since the product is not intended to be removed.  

### To Reproduce

The stack is from simply adding a product to the cart. I'm not familiar with the code or the purpose of the `SimulateCartEndpoint.php`, however here's the stack.

```
/sites/shop.wecoast.com.au/files/wp-includes/class-wp-hook.php(324): Reserved_Stock_Pro_Actions->cart_item_removed() #1 /sites/shop.wecoast.com.au/files/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #2 /sites/shop.wecoast.com.au/files/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /sites/shop.wecoast.com.au/files/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1315): do_action() #4 /sites/shop.wecoast.com.au/files/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Helper/CartProductsHelper.php(272): WC_Cart->remove_cart_item() #5 /sites/shop.wecoast.com.au/files/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/AbstractCartEndpoint.php(184): WooCommerce\PayPalCommerce\Button\Helper\CartProductsHelper->remove_cart_items() #6 /sites/shop.wecoast.com.au/files/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/SimulateCartEndpoint.php(162): WooCommerce\PayPalCommerce\Button\Endpoint\AbstractCartEndpoint->remove_cart_items() #7 /sites/shop.wecoast.com.au/files/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/SimulateCartEndpoint.php(84): WooCommerce\PayPalCommerce\Button\Endpoint\SimulateCartEndpoint->restore_real_cart() #8 /sites/shop.wecoast.com.au/files/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/AbstractCartEndpoint.php(73): WooCommerce\PayPalCommerce\Button\Endpoint\SimulateCartEndpoint->handle_data() #9 /sites/shop.wecoast.com.au/files/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule.php(133): WooCommerce\PayPalCommerce\Button\Endpoint\AbstractCartEndpoint->handle_request() #10 /sites/shop.wecoast.com.au/files/wp-includes/class-wp-hook.php(324): WooCommerce\PayPalCommerce\Button\ButtonModule::WooCommerce\PayPalCommerce\Button\{closure}() #11 /sites/shop.wecoast.com.au/files/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #12 /sites/shop.wecoast.com.au/files/wp-includes/plugin.php(517): WP_Hook->do_action() #13 /sites/shop.wecoast.com.au/files/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action() #14 /sites/shop.wecoast.com.au/files/wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax() #15 /sites/shop.wecoast.com.au/files/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #16 /sites/shop.wecoast.com.au/files/wp-includes/plugin.php(517): WP_Hook->do_action() #17 /sites/shop.wecoast.com.au/files/wp-includes/template-loader.php(13): do_action() #18 /sites/shop.wecoast.com.au/files/wp-blog-header.php(19): require_once('/sites/shop.wec...') #19 /sites/shop.wecoast.com.au/files/index.php(17): require('/sites/shop.wec...') #20 {main}
```
### Screenshots

![CleanShot 2024-02-08 at 16 19 05](https://github.com/woocommerce/woocommerce-paypal-payments/assets/10958823/d16c28f3-7ada-48bf-b859-0e2c154b78db)

From: https://github.com/woocommerce/woocommerce-paypal-payments/blob/eddb0b0bf37073e657570658fcb8e364f6130013/modules/ppcp-button/src/Endpoint/SimulateCartEndpoint.php#L166

### Expected Behavior

The cart itself shouldn't be altered since there's many plugins which provides additional validation and data during the various cart actions. We need those hooks run only when they are intended by the core.

**Comment by InpsydeNiklas** [comment]
Hi @morganhvidt, the cart simulation enhances some plugin features and helps with the compatibility for various third-party plugins or other customizations. But if it is causing any trouble for your use case, the plugin provides a couple of filters to disable it or adjust the timing: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#modify-cart-simulation-behavior
I hope this helps!
