### ISSUE TITLE
Retain Payment Tokens and Subscription features support - even if PayPal Payment is disabled for new Orders

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-paypal-payments#204]
### Describe the bug

If [PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/?aff=10486&cid=1131038) is disabled for new orders under **WooCommerce > Settings > Payments**, the Customer token and Support for [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038) disappears until it is enabled again. 

EDIT: **Note that even with the renewal failures, the subscription stays active.**

### To reproduce

1. Enable PayPal Payments, make sure `Vaulting` is enabled, and create a subscription:
    ![image](https://user-images.githubusercontent.com/17475174/127101758-ce37dbc6-77fc-428b-930d-2cdfc71939fe.png)

    ![image](https://user-images.githubusercontent.com/17475174/127101614-94e58b44-c059-45b5-87b5-583e681f557c.png)

2. Once the subscription is created, disable PayPal Payments from **WooCommerce > Settings > Payments**
3. Notice that support for Subscription is immediately missing:
    
    ![image](https://user-images.githubusercontent.com/17475174/127101480-df774105-81de-4ff8-8608-234b0ade64f4.png)
4. Let the Subscription renew automatically, or attempt to create a pending renewal order.

#### *Notice the following errors and order notes if you manually create a pending order:*

* **Critical Error** :

```
        2021-07-27T05:27:40+00:00 CRITICAL Uncaught Exception: Unable to change subscription status to "on-hold". in /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php:430
Stack trace:
        #0 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/admin/class-wcs-admin-meta-boxes.php(216): WC_Subscription->update_status('on-hold')
        #1 /wordpress/core/5.8/wp-includes/class-wp-hook.php(303): WCS_Admin_Meta_Boxes::create_pending_renewal_action_request(Object(WC_Subscription))
        #2 /wordpress/core/5.8/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
        #3 /wordpress/core/5.8/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
        #4 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php(139): do_action('woocommerce_ord...', Object(WC_Subscription))
        #5 /wordpress/core/5.8/wp-includes/class-wp-hook.php(303): WC_Meta_Box_Order_Actions::save(2042, Object(WP_Post))
        #6 /wordpress/core/5.8/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
        #7 /wordpress/core/5.8/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
        #8 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(222): do_action('woocommerce_pro...', 2042, Object(WP_Post))
        #9 /wordpress/core/5.8/wp-includes/class-wp-hook.php(305): WC_Admin_Meta_Boxes->save_meta_boxes(2042, Object(WP_Post))
        #10 /wordpress/core/5.8/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
        #11 /wordpress/core/5.8/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
        #12 /wordpress/core/5.8/wp-includes/post.php(4468): do_action('save_post', 2042, Object(WP_Post), true)
        #13 /wordpress/core/5.8/wp-includes/post.php(4570): wp_insert_post(Array, false, true)
        #14 /wordpress/core/5.8/wp-admin/includes/post.php(423): wp_update_post(Array)
        #15 /wordpress/core/5.8/wp-admin/post.php(227): edit_post()
        #16 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php on line 430
```

* **Subscription notes:** `Unable to change subscription status to “on-hold”.`

    
    ![image](https://user-images.githubusercontent.com/17475174/127102629-a35bffee-b122-404d-81a5-8b876fff32e5.png)

* PayPal Payments log: `2021-07-27T05:26:58+00:00 WARNING No token stored for customer 1.`

#### *Notice the following errors and order notes if you let scheduled actions do its job during renewal:*

* No Fatal errors
* **Dashboard notification:**

    ![https://d.pr/i/QWZuhx+](https://d.pr/i/QWZuhx+)

* **failed-scheduled-actions Logs**

```
07-27-2021 @ 06:01:33 - scheduled action 2559 (subscription payment) failed to finish processing due to the following exception: Unable to change subscription status to "on-hold".
07-27-2021 @ 06:01:33 - action args: subscription_id: 2042
```

* PayPal Payment logs

```
2021-07-27T05:56:26+00:00 ERROR Order 28B4-REDACTED-D is not approved yet.
```

### Expected behavior

Irrespective of if the payment gateway is enabled for new orders or not, existing renewals should go through successfully. 

**Environment (please complete the following information):**
 - WordPress Version: 5.8
 - WooCommerce Version: 5.5.2
 - WooCommerce PayPal Payments Plugin Version: 1.3.2
 - WooCommerce Subscription: 3.1.4
 - Browser [e.g. chrome, safari] and Version: N/A / Any

### Customer Reports

4110098-zen

**Comment by AashikP** [comment]
To add more context, since no Subscription features are supported with the payment method disabled for new orders, it is not just the renewals that are affected. 

Say you created a pending renewal order and ignore the critical error. The subscription stays on hold even though you pay for the order via a different payment gateway because the payment method does not support order status changes:

![https://d.pr/i/CN8rx7+](https://d.pr/i/CN8rx7+)

**Current workaround to the original report (subscription renewal)**

*   Temporarily enable PayPal Payments
*   Since the Subscription is still active, the Customer will be able to change the payment method to something else like [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/?aff=10486&cid=1131038) via **My Accounts > Subscription > View Subscription and click `Change Payment` button**
*   Once they change the payment method, you can charge them for renewal from WP Admin > Subscriptions > Edit Subscription page:
    
    ![https://d.pr/i/vLyXIy+](https://d.pr/i/vLyXIy+)
    _If the image does not load, please click this link: [https://d.pr/i/vLyXIy](https://d.pr/i/vLyXIy)_
    
*   You can then disable PayPal Payments
