### ISSUE TITLE
Orders Page Critical Error 

### ISSUE THREAD

**Issue by dlmdsmp555** [woocommerce/woocommerce-paypal-payments#2364]
### Describe the Bug

Some orders missing critical data ( email, address ) and order edit page appears totally blank.  
Email received stating that Paypal plugin caused error. 

" WordPress has a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.
>>
>> In this case, WordPress caught an error with one of your plugins, WooCommerce PayPal Payments."

![Screen Shot 2024-06-23 at 1 22 44 AM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/83384515/50035ba7-d231-434f-8a1f-9bcd5d00aad0)
![Screen Shot 2024-06-23 at 1 22 56 AM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/83384515/bbbf395d-25f7-41b6-b3ba-9b47af2180e5)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by lynnjat7** [comment]
another case here: 8332812-zen

**Comment by lynnjat7** [comment]
Stack trace:

```
Error Details
=============
An error of type E_ERROR was caused in line 484 of the file /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php. Error message: Uncaught WooCommerce\PayPalCommerce\ApiClient\Exception\RuntimeException: Could not retrieve order. in /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php:484
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/api/order-functions.php(48): WooCommerce\PayPalCommerce\ApiClient\Endpoint\OrderEndpoint->order('0KL95942E593763...')
#1 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/MetaBoxRenderer.php(96): WooCommerce\PayPalCommerce\Api\ppcp_get_paypal_order('0KL95942E593763...')
#2 /wordpress/core/6.5.4/wp-admin/includes/template.php(1456): WooCommerce\PayPalCommerce\OrderTracking\MetaBoxRenderer->render(Object(WP_Post), Array)
#3 /wordpress/core/6.5.4/wp-admin/edit-form-advanced.php(716): do_meta_boxes(Object(WP_Screen), 'side', Object(WP_Post))
#4 /wordpress/core/6.5.4/wp-admin/post.php(206): require('/wordpress/core...')
#5 {main}
  thrown
```

**Comment by InpsydeNiklas** [comment]
Hi @dlmdsmp555 @lynnjat7 , this issue was resolved in the latest [2.8.1-rc1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.8.1-rc1) pre-release version. Please give it a try and let us know if this resolves the issue for you. 
Thank you!

**Comment by jacobholes** [comment]
I also had the fatal error, 2.8.1-rc1 did indeed fix it for me.
