### ISSUE TITLE
Fatal Error causing woocommerce order to be created as Pending. Awaiting payment.

### ISSUE THREAD

**Issue by tonypoxon** [woocommerce/woocommerce-paypal-payments#2521]
2024-08-19T09:45:34+00:00 CRITICAL Uncaught Error: Call to a member function captures() on null in /var/www/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Processor/PaymentsStatusHandlingTrait.php:38 CONTEXT: {"error":{"type":1,"file":"/var/www/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Processor/PaymentsStatusHandlingTrait.php","line":38},"backtrace":["","#0 /var/www/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/CreditCardGateway.php(492): WooCommerce\PayPalCommerce\WcGateway\Gateway\CreditCardGateway->handle_new_order_status(Object(WooCommerce\PayPalCommerce\ApiClient\Entity\Order), Object(Automattic\WooCommerce\Admin\Overrides\Order))","#1 /var/www/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1062): WooCommerce\PayPalCommerce\WcGateway\Gateway\CreditCardGateway->process_payment(94364)","#2 /var/www/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1293): WC_Checkout->process_order_payment(94364, 'ppcp-credit-car...')","#3 /var/www/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(520): WC_Checkout->process_checkout()","#4 /var/www/wp-includes/class-wp-hook.php(324): WC_AJAX::checkout('')","#5 /var/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)","#6 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#7 /var/www/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action('wc_ajax_checkou...')","#8 /var/www/wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax('')","#9 /var/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(false, Array)","#10 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#11 /var/www/wp-includes/template-loader.php(13): do_action('template_redire...')","#12 /var/www/wp-blog-header.php(19): require_once('/var/www/wp-inc...')","#13 /var/www/index.php(17): require('/var/www/wp-blo...')","#14 {main}","thrown"]}

**Comment by callmeahmedr** [comment]
Fixed in PR #[2523](https://github.com/woocommerce/woocommerce-paypal-payments/pull/2523)

**Comment by InpsydeNiklas** [comment]
The fix mentioned above was shipped in the latest [2.9.0 release](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.0), so I'll close this issue. Thanks again!
