### ISSUE TITLE
Fatal error thrown on Connection tab

### ISSUE THREAD

**Issue by kuebk** [woocommerce/woocommerce-paypal-payments#2858]
### Describe the Bug

When trying to access `connection` tab in paypal payment method settings a fatal error is thrown

### To Reproduce

1. Go to `WooCommerce` in the admin menu
3. Click on `Settings`
4. Click on `Payments` tab
5. Click on `Manage` in PayPal payment method
6. Click on `Connetion` tab
7. See error

### Screenshots
-

### Expected Behavior

Connection settings can be edited

### Actual Behavior

Fatal error is thrown:
```
[28-Nov-2024 21:40:51 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function WooCommerce\PayPalCommerce\Uninstall\wp_create_nonce() in /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-uninstall/services.php:62
Stack trace:
#0 /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Inpsyde/Modularity/Container/ReadOnlyContainer.php(71): WooCommerce\PayPalCommerce\Uninstall\UninstallModule->WooCommerce\PayPalCommerce\Uninstall\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Inpsyde\Modularity\Container\ReadOnlyContainer))
#1 /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-uninstall/services.php(96): WooCommerce\PayPalCommerce\Vendor\Inpsyde\Modularity\Container\ReadOnlyContainer->get('uninstall.clear...')
#2 /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Inpsyde/Modularity/Container/ReadOnlyContainer.php(71): WooCommerce\PayPalCommerce\Uninstall\UninstallModule->WooCommerce\PayPalCommerce\Uninstall\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Inpsyde\Modularity\Container\ReadOnlyContainer))
#3 /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-uninstall/src/UninstallModule.php(48): WooCommerce\PayPalCommerce\Vendor\Inpsyde\Modularity\Container\ReadOnlyContainer->get('uninstall.clear...')
#4 /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Inpsyde/Modularity/Package.php(530): WooCommerce\PayPalCommerce\Uninstall\UninstallModule->run(Object(WooCommerce\PayPalCommerce\Vendor\Inpsyde\Modularity\Container\ReadOnlyContainer))
#5 /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Inpsyde/Modularity/Package.php(405): WooCommerce\PayPalCommerce\Vendor\Inpsyde\Modularity\Package->doExecute()
#6 /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/bootstrap.php(40): WooCommerce\PayPalCommerce\Vendor\Inpsyde\Modularity\Package->boot()
#7 /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php(77): {closure}('/home/xxx...')
#8 /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php(92): WooCommerce\PayPalCommerce\init()
#9 /home/xxx/public_html/wp-includes/class-wp-hook.php(324): WooCommerce\PayPalCommerce\{closure}('/home/xxx...')
#10 /home/xxx/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#11 /home/xxx/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/xxx/public_html/wp-settings.php(536): do_action('plugin_loaded', '/home/xxx...')
#13 /home/xxx/public_html/wp-config.php(100): require_once('/home/xxx...')
#14 /home/xxx/public_html/wp-load.php(50): require_once('/home/xxx...')
#15 /home/xxx/public_html/wp-admin/admin.php(34): require_once('/home/xxx...')
#16 {main}
  thrown in /home/xxx/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-uninstall/services.php on line 62
```

### Environment

 - WordPress Version: 6.7.1
 - WooCommerce Version: 9.4.2
 - Plugin Version: 2.9.4
 - Browser [e.g. Chrome, Safari] and Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - Any other plugins installed: yes

**Comment by kuebk** [comment]
Issue resolved by removing and installing plugin back.
