### ISSUE TITLE
Paypal 'PHP Fatal error: Uncaught Exception'

### ISSUE THREAD

**Issue by JacquieScarlett** [woocommerce/woocommerce-paypal-payments#2958]
### Describe the Bug

Hi
We have been experiencing the following error (below) on our server log since 23rd Dec. 
Payments are being made, captured and processed on our site but wonder what can be triggering this constant error message.

We had to switch off the ADVANCED CARD PAYMENTS option early in December as our e-commerce site was being inundated with FAILED & Fraudulent small orders due to some kind of vulnerability in the WooCommerce PayPal Payments plugin.

We would like to activate the Applepay & Googlepay options but feel that the plugin is unstable and i am loathe to make changes whilst it is plodding along.

Any advice would be gratefully received.

2024/12/31 12:33:06 [error] 49783#49783: *6980086 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Exception: The payment is not ready for processing yet. in /www/closshamblinltd_839/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Processor/OrderProcessor.php:234
Stack trace:
#0 /www/closshamblinltd_839/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/src/Handler/CheckoutOrderApproved.php(233): WooCommerce\PayPalCommerce\WcGateway\Processor\OrderProcessor->process(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /www/closshamblinltd_839/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/src/IncomingWebhookEndpoint.php(239): WooCommerce\PayPalCommerce\Webhooks\Handler\CheckoutOrderApproved->handle_request(Object(WP_REST_Request))
#2 /www/closshamblinltd_839/public/wp-includes/rest-api/class-wp-rest-server.php(1292): WooCommerce\PayPalCommerce\Webhooks\IncomingWebhookEndpoint->handle_request(Object(WP_REST_Request))
#3 /www/closshamblinltd_839/public/wp-includes/re" while reading response header from upstream, client: 173.0.81.140, server: candh.co.uk, request: "POST /wp-json/paypal/v1/incoming HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm-closshamblinltd.sock:", host: "candh.co.uk:20642"

### Environment

 - WordPress Version - 6.7.1
 - WooCommerce Version - 9.5.1
 - Plugin Version - 2.9.5
 - Browser [e.g. Chrome, Safari] and Version - Chrome 131.0.6778.205 (Official Build) (64-bit)
 - Any other plugins installed

### Additional Details

I can see that this error message has been reported before and there seems to be no offered solution.

<details><summary>System status</summary>

  `
### WordPress Environment ###

WC Version: 9.5.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.5
PHP Version: 8.1.30
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.11.5-MariaDB-1:10.11.5+maria~ubu2004
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.5.1
WC Database Prefix: UHWlCjrm
Total Database Size: 1789.18MB
Database Data Size: 1096.15MB
Database Index Size: 693.03MB
UHWlCjrmwoocommerce_sessions: Data: 163.19MB + Index: 5.02MB + Engine InnoDB
UHWlCjrmwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UHWlCjrmwoocommerce_order_items: Data: 2.52MB + Index: 0.48MB + Engine InnoDB
UHWlCjrmwoocommerce_order_itemmeta: Data: 13.50MB + Index: 9.92MB + Engine InnoDB
UHWlCjrmwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UHWlCjrmwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
UHWlCjrmwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmwoocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmactionscheduler_actions: Data: 28.05MB + Index: 21.11MB + Engine InnoDB
UHWlCjrmactionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmactionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmactionscheduler_logs: Data: 17.05MB + Index: 14.03MB + Engine InnoDB
UHWlCjrmaioseo_cache: Data: 0.23MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmaioseo_notifications: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
UHWlCjrmaioseo_posts: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmcc_condition: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmcc_discounts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmcc_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcc_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmcc_form_fields_attributes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmcc_orders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
UHWlCjrmcc_payments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmcc_promocodes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmcky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmcmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcmplz_cookies: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcommentmeta: Data: 0.22MB + Index: 0.66MB + Engine InnoDB
UHWlCjrmcomments: Data: 28.38MB + Index: 25.95MB + Engine InnoDB
UHWlCjrmcommercekit_searches: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcommercekit_swatches_cache_count: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcommercekit_waitlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcommercekit_wishlist: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcommercekit_wishlist_items: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcp_calculated_fields_form_discount_codes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcp_calculated_fields_form_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcp_calculated_fields_form_revision: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmcp_calculated_fields_form_settings: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
UHWlCjrme_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmfrm_fields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmfrm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmfrm_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
UHWlCjrmfrm_item_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmgla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmgla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
UHWlCjrmgla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmgla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmgla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmjetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UHWlCjrmjetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmlinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmmailchimp_carts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmmailchimp_jobs: Data: 3.38MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmmasterslider_options: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmmasterslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmoptions: Data: 115.08MB + Index: 11.08MB + Engine InnoDB
UHWlCjrmpopup_box: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmpostmeta: Data: 390.55MB + Index: 424.31MB + Engine InnoDB
UHWlCjrmposts: Data: 150.09MB + Index: 18.44MB + Engine InnoDB
UHWlCjrmpp_activity_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmsmush_dir_images: Data: 0.42MB + Index: 0.19MB + Engine InnoDB
UHWlCjrmsnippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmtermmeta: Data: 0.17MB + Index: 0.42MB + Engine InnoDB
UHWlCjrmterms: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
UHWlCjrmterm_relationships: Data: 10.50MB + Index: 6.36MB + Engine InnoDB
UHWlCjrmterm_taxonomy: Data: 0.27MB + Index: 0.14MB + Engine InnoDB
UHWlCjrmuserfeedback_surveys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmuserfeedback_survey_responses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmusermeta: Data: 42.25MB + Index: 101.52MB + Engine InnoDB
UHWlCjrmusers: Data: 3.52MB + Index: 5.94MB + Engine InnoDB
UHWlCjrmwcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwc_customer_lookup: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
UHWlCjrmwc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmwc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
UHWlCjrmwc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmwc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UHWlCjrmwc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmwc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmwc_order_product_lookup: Data: 1.52MB + Index: 0.88MB + Engine InnoDB
UHWlCjrmwc_order_stats: Data: 1.50MB + Index: 0.64MB + Engine InnoDB
UHWlCjrmwc_order_tax_lookup: Data: 0.45MB + Index: 0.38MB + Engine InnoDB
UHWlCjrmwc_product_attributes_lookup: Data: 8.41MB + Index: 6.28MB + Engine InnoDB
UHWlCjrmwc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwc_product_meta_lookup: Data: 4.50MB + Index: 10.47MB + Engine InnoDB
UHWlCjrmwc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwf301_404_logs: Data: 7.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwf301_linkhero: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwf301_redirect_logs: Data: 7.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwf301_redirect_rules: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfauditevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
UHWlCjrmwfconfig: Data: 2.28MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwffilemods: Data: 18.55MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfhits: Data: 7.02MB + Index: 0.22MB + Engine InnoDB
UHWlCjrmwfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UHWlCjrmwfknownfilelist: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwflogins: Data: 0.45MB + Index: 0.17MB + Engine InnoDB
UHWlCjrmwfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmwfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
UHWlCjrmwfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfnotifications: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UHWlCjrmwfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
UHWlCjrmwfstatus: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
UHWlCjrmwftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwpforms_entries: Data: 10.11MB + Index: 0.42MB + Engine InnoDB
UHWlCjrmwpforms_entry_fields: Data: 5.13MB + Index: 7.09MB + Engine InnoDB
UHWlCjrmwpforms_entry_meta: Data: 1.28MB + Index: 0.27MB + Engine InnoDB
UHWlCjrmwpforms_logs: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
UHWlCjrmwpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
UHWlCjrmwpforms_tasks_meta: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwpforms_user_journey: Data: 1.34MB + Index: 0.13MB + Engine InnoDB
UHWlCjrmwpmailsmtp_debug_events: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UHWlCjrmwt_sc_coupon_lookup: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
UHWlCjrmyoast_indexable: Data: 23.22MB + Index: 10.92MB + Engine InnoDB
UHWlCjrmyoast_indexable_hierarchy: Data: 2.17MB + Index: 3.31MB + Engine InnoDB
UHWlCjrmyoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UHWlCjrmyoast_primary_term: Data: 1.50MB + Index: 2.84MB + Engine InnoDB
UHWlCjrmyoast_seo_links: Data: 1.13MB + Index: 0.38MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 30045
cost-calc: 113
cost-calc-categories: 10
cost-calc-templates: 101
custom_css: 2
customize_changeset: 2
e-landing-page: 1
elementor_library: 2
feedback: 220
frm_form_actions: 3
frm_styles: 1
jetpack-testimonial: 2
jp_img_sitemap: 12
jp_img_sitemap_index: 1
jp_sitemap: 7
jp_sitemap_index: 1
jp_sitemap_master: 1
mailpoet_page: 1
nav_menu_item: 234
oembed_cache: 2
page: 187
post: 19
product: 13941
product_variation: 4759
revision: 287
seedprod: 1
shop_coupon: 87
shop_order: 5615
shop_order_refund: 893
wb-custom-tabs: 6
wc_mmqw: 1
woo_product_tab: 8
wp_block: 1
wp_global_styles: 2
wp_navigation: 1
wpforms: 18
wppopups: 1
wpsl_stores: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (45) ###

301 Redirects Pro: by WebFactory Ltd – 6.22
Advanced Database Cleaner: by Younes JFR. – 3.1.5
Block Visibility: by Nick Diego – 3.7.1
Calculated Fields Form: by CodePeople – 5.3.10
Classic Widgets: by WordPress Contributors – 0.3
Code Snippets: by Code Snippets Pro – 3.6.6.1
CommerceGurus CommerceKit: by CommerceGurus – 2.2.4
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 7.1.5
Cost Calculator Builder: by StylemixThemes – 3.2.55
Cost of Goods: Product Cost & Profit Calculator for WooCommerce: by WPFactory – 3.6.1
Customizer Export/Import: by The Beaver Builder Team – 0.9.7.3
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.20.3
EAN for WooCommerce Pro: by WPFactory – 4.9.1
EAN Barcode Generator for WooCommerce: UPC, ISBN & GTIN Inventory: by WPFactory – 5.3.5
Folders: by Premio – 3.0.6
Site Kit by Google: by Google – 1.142.0
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.5.2

Jetpack Boost: by Automattic - Jetpack Site Speed team – 3.6.1
Jetpack: by Automattic – 14.1
Kirki Customizer Framework: by Themeum – 5.1.0
Mailchimp for WooCommerce: by Mailchimp – 5.0
Mailchimp: by Mailchimp – 1.6.2
Perfect Brands WooCommerce: by QuadLayers – 3.4.7
Query Monitor: by John Blackbourn – 3.17.0
Supplier Order Email: by MCI Desarrollo – 3.6.9
Product Search Category Redirect: by 99w – 1.4.1
CTX Feed: by WebAppick – 6.5.41
WooCommerce PayPal Payments: by WooCommerce – 2.9.5
WooCommerce Product Tabs (Free): by Barn2 Plugins – 2.1.8
WooCommerce Shipping & Tax: by WooCommerce – 2.8.5
WooCommerce: by Automattic – 9.5.1
Wordfence Security: by Wordfence – 8.0.1
WordPress Importer: by wordpressdotorg – 0.8.3
Yoast SEO: by Team Yoast – 24.1
WP Crontrol: by John Blackbourn – 1.17.1
WP File Manager: by mndpsingh287 – 8.0
WP Mail SMTP: by WP Mail SMTP – 4.3.0
WP Rollback: by WP Rollback – 2.0.7
Smush: by WPMU DEV – 3.16.6
WP Store Locator: by Tijmen Smit – 2.2.241
WPForms User Journey: by WPForms – 1.4.0
WPForms: by WPForms – 1.9.2.3
Smart Coupons For WooCommerce Coupons: by WebToffee – 1.8.5
Yoast Test Helper: by Team Yoast – 1.18

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (2) ###

Index WP MySQL For Speed Upgrade Filter for mu-plugins.: by  – 1.4.12
Kinsta Must-use Plugins: by Kinsta Team – 3.1.1

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 23 MB

### WC Pages ###

Shop base: ❌ Page not set
Basket: #19 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #20 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #21 - /my-account/
Terms and conditions: #49221 - /terms-and-conditions/

### Theme ###

Name: Shoptimizer Child Theme
Version: 1.2.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Shoptimizer
Parent Theme Version: 2.8.3
Parent Theme Author URL: https://www.commercegurus.com/
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: shoptimizer-child-theme/woocommerce/emails/admin-cancelled-order.php
shoptimizer-child-theme/woocommerce/emails/customer-completed-order.php
shoptimizer-child-theme/woocommerce/emails/customer-on-hold-order.php
shoptimizer-child-theme/woocommerce/emails/customer-processing-order.php
shoptimizer-child-theme/woocommerce/emails/customer-refunded-order.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout

Daily Cron: ✔ Next scheduled: 2025-01-01 10:21:30 +00:00
Options: ✔
Notes: 26
Onboarding: completed

### Action Scheduler ###

Canceled: 5
Oldest: 2024-12-23 10:05:29 +0000
Newest: 2024-12-01 09:07:40 +0000

Complete: 16,066
Oldest: 2024-12-20 15:32:41 +0000
Newest: 2024-12-31 12:37:45 +0000

Failed: 7,465
Oldest: 2022-10-20 10:57:51 +0100
Newest: 2024-12-24 09:07:41 +0000

Pending: 15
Oldest: 2024-12-31 15:59:40 +0000
Newest: 2025-01-07 02:07:33 +0000

### Status report information ###

Generated at: 2024-12-31 13:20:40 +00:00
`

</details>

**Comment by leadnerds** [comment]
I am having the same issue and hope to see a resolution

**Comment by SydeKrystian** [comment]
Hello @JacquieScarlett & @leadnerds 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
